snap_bone_fixed_name_list = [
    # 躯干
    ['Hips', 'MhBone_013'],
    ['Spine', 'MhBone_001'],
    ['Chest', 'MhBone_002'],
    ['Neck', 'MhBone_003'],
    ['Head', 'MhBone_004'],
    ['Neck', 'MhBone_254'],
    # 左臂
    ['Left shoulder', 'MhBone_005'],
    ['Left arm', 'MhBone_006'],
    ['Left elbow', 'MhBone_007'],
    ['Left wrist', 'MhBone_008'],
    ['Left wrist', 'MhBone_030'],
    ['Thumb0_L', 'MhBone_031'],
    ['Thumb1_L', 'MhBone_032'],
    ['Thumb2_L', 'MhBone_033'],
    ['IndexFinger1_L', 'MhBone_034'],
    ['IndexFinger2_L', 'MhBone_035'],
    ['IndexFinger3_L', 'MhBone_036'],
    ['MiddleFinger1_L', 'MhBone_037'],
    ['MiddleFinger2_L', 'MhBone_038'],
    ['MiddleFinger3_L', 'MhBone_039'],
    ['Left wrist', 'MhBone_040'],
    ['RingFinger1_L', 'MhBone_041'],
    ['RingFinger2_L', 'MhBone_042'],
    ['RingFinger3_L', 'MhBone_043'],
    ['LittleFinger1_L', 'MhBone_044'],
    ['LittleFinger2_L', 'MhBone_045'],
    ['LittleFinger3_L', 'MhBone_046'],
    # 右臂
    ['Right shoulder', 'MhBone_009'],
    ['Right arm', 'MhBone_010'],
    ['Right elbow', 'MhBone_011'],
    ['Right wrist', 'MhBone_012'],
    ['Right wrist', 'MhBone_047'],
    ['Thumb0_R', 'MhBone_048'],
    ['Thumb1_R', 'MhBone_049'],
    ['Thumb2_R', 'MhBone_050'],
    ['IndexFinger1_R', 'MhBone_051'],
    ['IndexFinger2_R', 'MhBone_052'],
    ['IndexFinger3_R', 'MhBone_053'],
    ['MiddleFinger1_R', 'MhBone_054'],
    ['MiddleFinger2_R', 'MhBone_055'],
    ['MiddleFinger3_R', 'MhBone_056'],
    ['Right wrist', 'MhBone_057'],
    ['RingFinger1_R', 'MhBone_058'],
    ['RingFinger2_R', 'MhBone_059'],
    ['RingFinger3_R', 'MhBone_060'],
    ['LittleFinger1_R', 'MhBone_061'],
    ['LittleFinger2_R', 'MhBone_062'],
    ['LittleFinger3_R', 'MhBone_063'],
    # 腿部
    ['Left leg', 'MhBone_014'],
    ['Left knee', 'MhBone_015'],
    ['Left ankle', 'MhBone_016'],
    ['Left toe', 'MhBone_017'],
    ['Right leg', 'MhBone_018'],
    ['Right knee', 'MhBone_019'],
    ['Right ankle', 'MhBone_020'],
    ['Right toe', 'MhBone_021'],
    # 辅助骨骼
    ['Left arm', 'MhBone_070'],
    ['Left elbow', 'MhBone_071'],
    ['Left arm', 'MhBone_080'],
    ['zHandTwist_L', 'MhBone_081'],
    ['Right arm', 'MhBone_072'],
    ['Right elbow', 'MhBone_073'],
    ['Right arm', 'MhBone_082'],
    ['zHandTwist_R', 'MhBone_083'],
    ['Left leg', 'MhBone_074'],
    ['Left knee', 'MhBone_075'],
    ['Left ankle', 'MhBone_084'],
    ['Right leg', 'MhBone_076'],
    ['Right knee', 'MhBone_077'],
    ['Right ankle', 'MhBone_085'],
]

rename_vg_fixed_name_list = [
    # 躯干
    ['Hips', 'MhBone_013'],
    ['Spine', 'MhBone_001'],
    ['Chest', 'MhBone_002'],
    ['Neck', 'MhBone_003'],
    ['Head', 'MhBone_004'],
    # 左臂
    ['Left shoulder', 'MhBone_005'],
    ['zArmTwist_L', 'MhBone_006'],
    ['Left elbow', 'MhBone_007'],
    ['Left wrist', 'MhBone_008'],
    ['Thumb0_L', 'MhBone_031'],
    ['Thumb1_L', 'MhBone_032'],
    ['Thumb2_L', 'MhBone_033'],
    ['IndexFinger1_L', 'MhBone_034'],
    ['IndexFinger2_L', 'MhBone_035'],
    ['IndexFinger3_L', 'MhBone_036'],
    ['MiddleFinger1_L', 'MhBone_037'],
    ['MiddleFinger2_L', 'MhBone_038'],
    ['MiddleFinger3_L', 'MhBone_039'],
    ['自定义L', 'MhBone_040'],
    ['RingFinger1_L', 'MhBone_041'],
    ['RingFinger2_L', 'MhBone_042'],
    ['RingFinger3_L', 'MhBone_043'],
    ['LittleFinger1_L', 'MhBone_044'],
    ['LittleFinger2_L', 'MhBone_045'],
    ['LittleFinger3_L', 'MhBone_046'],
    # 右臂
    ['Right shoulder', 'MhBone_009'],
    ['zArmTwist_R', 'MhBone_010'],
    ['Right elbow', 'MhBone_011'],
    ['Right wrist', 'MhBone_012'],
    ['Thumb0_R', 'MhBone_048'],
    ['Thumb1_R', 'MhBone_049'],
    ['Thumb2_R', 'MhBone_050'],
    ['IndexFinger1_R', 'MhBone_051'],
    ['IndexFinger2_R', 'MhBone_052'],
    ['IndexFinger3_R', 'MhBone_053'],
    ['MiddleFinger1_R', 'MhBone_054'],
    ['MiddleFinger2_R', 'MhBone_055'],
    ['MiddleFinger3_R', 'MhBone_056'],
    ['自定义R', 'MhBone_057'],
    ['RingFinger1_R', 'MhBone_058'],
    ['RingFinger2_R', 'MhBone_059'],
    ['RingFinger3_R', 'MhBone_060'],
    ['LittleFinger1_R', 'MhBone_061'],
    ['LittleFinger2_R', 'MhBone_062'],
    ['LittleFinger3_R', 'MhBone_063'],
    # 腿部
    ['Left leg', 'MhBone_014'],
    ['Left knee', 'MhBone_015'],
    ['Left ankle', 'MhBone_016'],
    ['Left toe', 'MhBone_017'],
    ['Right leg', 'MhBone_018'],
    ['Right knee', 'MhBone_019'],
    ['Right ankle', 'MhBone_020'],
    ['Right toe', 'MhBone_021'],
    # 辅助骨骼
    ['自定义1', 'MhBone_070'],
    ['+ElbowAux_L', 'MhBone_071'],
    ['ElbowAux_L', 'MhBone_071'],
    ['Left arm', 'MhBone_080'],
    ['zHandTwist_L', 'MhBone_081'],
    ['自定义5', 'MhBone_072'],
    ['+ElbowAux_R', 'MhBone_073'],
    ['ElbowAux_R', 'MhBone_073'],
    ['Right arm', 'MhBone_082'],
    ['zHandTwist_R', 'MhBone_083'],
    ['OhButt_L', 'MhBone_074'],
    ['+KneeAux_L', 'MhBone_075'],
    ['KneeAux_L', 'MhBone_075'],
    ['自定义11', 'MhBone_084'],
    ['OhButt_R', 'MhBone_076'],
    ['+KneeAux_R', 'MhBone_077'],
    ['KneeAux_R', 'MhBone_077'],
    ['自定义14', 'MhBone_085'],
]

snap_mmd_corrections = True
