# 编写字典时最好按照骨骼层级的顺序来编写，简单来说就是胯到胸到头，左臂到左手，右臂到右手，左腿到左脚，右腿到右脚。
# 注意，请确保rename_vg_fixed_name_list字典中的前5个骨骼名，普遍都存在于该字典对应的一类外部骨架中，插件会用于判定选择的字典是否匹配当前选中的外部骨架。

snap_bone_fixed_name_list = [
            ['MhBone_013', 'Hip'],
            ['MhBone_001', 'Spine_0'],
            ['MhBone_002', 'Spine_1'],
            ['MhBone_002', 'Spine_2'],
            ['MhBone_003', 'Neck_0'],
            ['MhBone_003', 'Neck_0_HJ_00'],

            ['MhBone_004', 'Head'],

            ['MhBone_005', 'L_Shoulder'],
            ['MhBone_080', 'L_UpperArm'],
            ['MhBone_007', 'L_Forearm'],
            ['MhBone_008', 'L_Hand'],
            ['MhBone_008', 'L_Wep'],

            ['MhBone_031', 'L_Thumb1'],
            ['MhBone_032', 'L_Thumb2'],
            ['MhBone_033', 'L_Thumb3'],

            ['MhBone_031', 'L_Thumb_HJ_00'],
            ['MhBone_032', 'L_Thumb_HJ_01'],
            ['MhBone_033', 'L_Thumb_HJ_02'],
            ['MhBone_031', 'L_Thumb_HJ_03'],

            ['MhBone_034', 'L_IndexF1'],
            ['MhBone_035', 'L_IndexF2'],
            ['MhBone_036', 'L_IndexF3'],

            ['MhBone_034', 'L_IndexF_HJ_01'],
            ['MhBone_035', 'L_IndexF_HJ_02'],
            ['MhBone_036', 'L_IndexF_HJ_03'],
            ['MhBone_034', 'L_IndexF_HJ_00'],
            ['MhBone_034', 'L_IndexF_HJ_04'],

            ['MhBone_037', 'L_MiddleF1'],
            ['MhBone_038', 'L_MiddleF2'],
            ['MhBone_039', 'L_MiddleF3'],

            ['MhBone_037', 'L_MiddleF_HJ_01'],
            ['MhBone_038', 'L_MiddleF_HJ_02'],
            ['MhBone_039', 'L_MiddleF_HJ_03'],
            ['MhBone_037', 'L_MiddleF_HJ_00'],
            ['MhBone_037', 'L_MiddleF_HJ_04'],

            ['MhBone_040', 'L_Palm'],

            ['MhBone_041', 'L_RingF1'],
            ['MhBone_042', 'L_RingF2'],
            ['MhBone_043', 'L_RingF3'],

            ['MhBone_041', 'L_RingF_HJ_01'],
            ['MhBone_042', 'L_RingF_HJ_02'],
            ['MhBone_043', 'L_RingF_HJ_03'],
            ['MhBone_041', 'L_RingF_HJ_00'],
            ['MhBone_041', 'L_RingF_HJ_04'],

            ['MhBone_044', 'L_PinkyF1'],
            ['MhBone_045', 'L_PinkyF2'],
            ['MhBone_046', 'L_PinkyF3'],

            ['MhBone_044', 'L_PinkyF_HJ_01'],
            ['MhBone_045', 'L_PinkyF_HJ_02'],
            ['MhBone_046', 'L_PinkyF_HJ_03'],
            ['MhBone_044', 'L_PinkyF_HJ_00'],
            ['MhBone_044', 'L_PinkyF_HJ_04'],

            ['MhBone_008', 'L_HandRZ_HJ_00'],
            ['MhBone_008', 'L_Hand_HJ_01'],
            ['MhBone_008', 'L_Wep_Sub'],
            ['MhBone_008', 'L_Hand_HJ_00'],

            ['MhBone_081', 'L_ForearmTwist_HJ_02'],
            ['MhBone_007', 'L_ForearmRY_HJ_00'],
            ['MhBone_007', 'L_ForearmRY_HJ_01'],
            ['MhBone_081', 'L_ForearmTwist_HJ_01'],
            ['MhBone_007', 'L_ForearmTwist_HJ_00'],
            ['MhBone_007', 'L_Forearm_HJ_00'],
            ['MhBone_007', 'L_Elbow_HJ_00'],

            ['MhBone_080', 'L_UpperArmTwist_HJ_00'],

            ['MhBone_006', 'L_UpperArmTwist_HJ_01'],
            ['MhBone_006', 'L_Triceps_HJ_00'],
            ['MhBone_006', 'L_Biceps_HJ_00'],
            ['MhBone_006', 'L_Biceps_HJ_01'],
            ['MhBone_006', 'L_UpperArmTwist_HJ_02'],

            ['MhBone_007', 'L_ForearmDouble_HJ_00'],
            ['MhBone_080', 'L_UpperArm_HJ_00'],
            ['MhBone_080', 'L_Deltoid_HJ_00'],
            ['MhBone_080', 'L_Deltoid_HJ_01'],
            ['MhBone_080', 'L_Deltoid_HJ_02'],
            ['MhBone_080', 'L_UpperArmDouble_HJ_00'],

            ['MhBone_005', 'L_Shoulder_HJ_00'],

            ['MhBone_009', 'R_Shoulder'],
            ['MhBone_082', 'R_UpperArm'],
            ['MhBone_011', 'R_Forearm'],
            ['MhBone_012', 'R_Hand'],
            ['MhBone_012', 'R_Wep'],

            ['MhBone_048', 'R_Thumb1'],
            ['MhBone_049', 'R_Thumb2'],
            ['MhBone_050', 'R_Thumb3'],

            ['MhBone_048', 'R_Thumb_HJ_00'],
            ['MhBone_049', 'R_Thumb_HJ_01'],
            ['MhBone_050', 'R_Thumb_HJ_02'],
            ['MhBone_048', 'R_Thumb_HJ_03'],

            ['MhBone_051', 'R_IndexF1'],
            ['MhBone_052', 'R_IndexF2'],
            ['MhBone_053', 'R_IndexF3'],

            ['MhBone_051', 'R_IndexF_HJ_01'],
            ['MhBone_052', 'R_IndexF_HJ_02'],
            ['MhBone_053', 'R_IndexF_HJ_03'],
            ['MhBone_051', 'R_IndexF_HJ_00'],
            ['MhBone_051', 'R_IndexF_HJ_04'],

            ['MhBone_054', 'R_MiddleF1'],
            ['MhBone_055', 'R_MiddleF2'],
            ['MhBone_056', 'R_MiddleF3'],

            ['MhBone_054', 'R_MiddleF_HJ_01'],
            ['MhBone_055', 'R_MiddleF_HJ_02'],
            ['MhBone_056', 'R_MiddleF_HJ_03'],
            ['MhBone_054', 'R_MiddleF_HJ_00'],
            ['MhBone_054', 'R_MiddleF_HJ_04'],

            ['MhBone_057', 'R_Palm'],

            ['MhBone_058', 'R_RingF1'],
            ['MhBone_059', 'R_RingF2'],
            ['MhBone_060', 'R_RingF3'],

            ['MhBone_058', 'R_RingF_HJ_01'],
            ['MhBone_059', 'R_RingF_HJ_02'],
            ['MhBone_060', 'R_RingF_HJ_03'],
            ['MhBone_058', 'R_RingF_HJ_00'],
            ['MhBone_058', 'R_RingF_HJ_04'],

            ['MhBone_061', 'R_PinkyF1'],
            ['MhBone_062', 'R_PinkyF2'],
            ['MhBone_063', 'R_PinkyF3'],

            ['MhBone_061', 'R_PinkyF_HJ_01'],
            ['MhBone_062', 'R_PinkyF_HJ_02'],
            ['MhBone_063', 'R_PinkyF_HJ_03'],
            ['MhBone_061', 'R_PinkyF_HJ_00'],
            ['MhBone_061', 'R_PinkyF_HJ_04'],

            ['MhBone_012', 'R_HandRZ_HJ_00'],
            ['MhBone_012', 'R_Hand_HJ_01'],
            ['MhBone_012', 'R_Wep_Sub'],
            ['MhBone_012', 'R_Hand_HJ_00'],

            ['MhBone_083', 'R_ForearmTwist_HJ_02'],
            ['MhBone_011', 'R_ForearmRY_HJ_00'],
            ['MhBone_011', 'R_ForearmRY_HJ_01'],
            ['MhBone_083', 'R_ForearmTwist_HJ_01'],
            ['MhBone_011', 'R_ForearmTwist_HJ_00'],
            ['MhBone_011', 'R_Shield'],
            ['MhBone_011', 'R_Forearm_HJ_00'],
            ['MhBone_011', 'R_Elbow_HJ_00'],

            ['MhBone_082', 'R_UpperArmTwist_HJ_00'],

            ['MhBone_010', 'R_UpperArmTwist_HJ_01'],
            ['MhBone_010', 'R_Triceps_HJ_00'],
            ['MhBone_010', 'R_Biceps_HJ_00'],
            ['MhBone_010', 'R_Biceps_HJ_01'],
            ['MhBone_010', 'R_UpperArmTwist_HJ_02'],

            ['MhBone_011', 'R_ForearmDouble_HJ_00'],
            ['MhBone_082', 'R_UpperArm_HJ_00'],
            ['MhBone_082', 'R_Deltoid_HJ_00'],
            ['MhBone_082', 'R_Deltoid_HJ_01'],
            ['MhBone_082', 'R_Deltoid_HJ_02'],
            ['MhBone_082', 'R_UpperArmDouble_HJ_00'],

            ['MhBone_009', 'R_Shoulder_HJ_00'],

            ['MhBone_005', 'L_Traps_HJ_00'],
            ['MhBone_005', 'L_Traps_HJ_01'],
            ['MhBone_005', 'L_Pec_HJ_00'],
            ['MhBone_005', 'L_Pec_HJ_01'],
            ['MhBone_005', 'L_Lats_HJ_00'],
            ['MhBone_005', 'L_Lats_HJ_01'],

            ['MhBone_009', 'R_Traps_HJ_00'],
            ['MhBone_009', 'R_Traps_HJ_01'],
            ['MhBone_009', 'R_Pec_HJ_00'],
            ['MhBone_009', 'R_Pec_HJ_01'],
            ['MhBone_009', 'R_Lats_HJ_00'],
            ['MhBone_009', 'R_Lats_HJ_01'],

            ['MhBone_002', 'Spine_2_HJ_00'],

            #    ['','R_Bust_HJ_00'],
            #    ['','R_Bust_HJ_01'],
            #    ['','L_Bust_HJ_00'],
            #    ['','L_Bust_HJ_01'],

            ['MhBone_002', 'Spine_1_HJ_00'],
            ['MhBone_001', 'Spine_0_HJ_00'],

            ['MhBone_014', 'L_Thigh'],
            ['MhBone_015', 'L_Knee'],
            ['MhBone_015', 'L_Shin'],
            ['MhBone_016', 'L_Foot'],

            ['MhBone_017', 'L_Toe'],
            ['MhBone_016', 'L_Foot_HJ_00'],
            ['MhBone_015', 'L_Calf_HJ_00'],
            ['MhBone_015', 'L_Shin_HJ_00'],
            ['MhBone_015', 'L_Shin_HJ_01'],
            ['MhBone_015', 'L_Knee_HJ_00'],
            ['MhBone_015', 'L_KneeDouble_HJ_00'],
            ['MhBone_015', 'L_KneeRX_HJ_00'],
            ['MhBone_014', 'L_ThighTwist_HJ_00'],
            ['MhBone_014', 'L_ThighTwist_HJ_01'],
            ['MhBone_015', 'L_ThighTwist_HJ_02'],

            ['MhBone_018', 'R_Thigh'],
            ['MhBone_019', 'R_Knee'],
            ['MhBone_019', 'R_Shin'],
            ['MhBone_020', 'R_Foot'],

            ['MhBone_021', 'R_Toe'],
            ['MhBone_020', 'R_Foot_HJ_00'],
            ['MhBone_019', 'R_Calf_HJ_00'],
            ['MhBone_019', 'R_Shin_HJ_00'],
            ['MhBone_019', 'R_Shin_HJ_01'],
            ['MhBone_019', 'R_Knee_HJ_00'],
            ['MhBone_019', 'R_KneeDouble_HJ_00'],
            ['MhBone_019', 'R_KneeRX_HJ_00'],
            ['MhBone_018', 'R_ThighTwist_HJ_00'],
            ['MhBone_018', 'R_ThighTwist_HJ_01'],
            ['MhBone_019', 'R_ThighTwist_HJ_02'],

            ['MhBone_014', 'L_ThighRZ_HJ_00'],
            ['MhBone_014', 'L_ThighRZ_HJ_01'],
            ['MhBone_018', 'R_ThighRZ_HJ_00'],
            ['MhBone_018', 'R_ThighRZ_HJ_01'],
            ['MhBone_014', 'L_Hip_HJ_00'],
            ['MhBone_014', 'L_Hip_HJ_01'],
            ['MhBone_018', 'R_Hip_HJ_00'],
            ['MhBone_018', 'R_Hip_HJ_01'],
            ['MhBone_014', 'L_ThighRX_HJ_00'],
            ['MhBone_014', 'L_ThighRX_HJ_01'],
            ['MhBone_018', 'R_ThighRX_HJ_00'],
            ['MhBone_018', 'R_ThighRX_HJ_01'],

            ['MhBone_013', 'Hip_HJ_00'],
        ]
        
rename_vg_fixed_name_list = [
            ['MhBone_000', 'COG'],
            ['MhBone_013', 'Hip_HJ_00'],
            ['MhBone_001', 'Spine_0_HJ_00'],
            ['MhBone_002', 'Spine_1_HJ_00'],
            ['MhBone_003', 'Neck_0_HJ_00'],
            ['MhBone_004', 'Head'],

            ['MhBone_005', 'L_Shoulder_HJ_00'],
            ['MhBone_006', 'L_UpperArmTwist_HJ_01'],
            ['MhBone_007', 'L_ForearmTwist_HJ_00'],
            ['MhBone_008', 'L_Hand'],
            ['MhBone_031', 'L_Thumb1'],
            ['MhBone_032', 'L_Thumb2'],
            ['MhBone_033', 'L_Thumb3'],
            ['MhBone_034', 'L_IndexF1'],
            ['MhBone_035', 'L_IndexF2'],
            ['MhBone_036', 'L_IndexF3'],
            ['MhBone_037', 'L_MiddleF1'],
            ['MhBone_038', 'L_MiddleF2'],
            ['MhBone_039', 'L_MiddleF3'],
            ['MhBone_040', 'L_Palm'],
            ['MhBone_041', 'L_RingF1'],
            ['MhBone_042', 'L_RingF2'],
            ['MhBone_043', 'L_RingF3'],
            ['MhBone_044', 'L_PinkyF1'],
            ['MhBone_045', 'L_PinkyF2'],
            ['MhBone_046', 'L_PinkyF3'],

            ['MhBone_009', 'R_Shoulder_HJ_00'],
            ['MhBone_010', 'R_UpperArmTwist_HJ_01'],
            ['MhBone_011', 'R_ForearmTwist_HJ_00'],
            ['MhBone_012', 'R_Hand'],
            ['MhBone_048', 'R_Thumb1'],
            ['MhBone_049', 'R_Thumb2'],
            ['MhBone_050', 'R_Thumb3'],
            ['MhBone_051', 'R_IndexF1'],
            ['MhBone_052', 'R_IndexF2'],
            ['MhBone_053', 'R_IndexF3'],
            ['MhBone_054', 'R_MiddleF1'],
            ['MhBone_055', 'R_MiddleF2'],
            ['MhBone_056', 'R_MiddleF3'],
            ['MhBone_057', 'R_Palm'],
            ['MhBone_058', 'R_RingF1'],
            ['MhBone_059', 'R_RingF2'],
            ['MhBone_060', 'R_RingF3'],
            ['MhBone_061', 'R_PinkyF1'],
            ['MhBone_062', 'R_PinkyF2'],
            ['MhBone_063', 'R_PinkyF3'],

            ['MhBone_014', 'L_Thigh'],
            ['MhBone_015', 'L_Shin'],
            ['MhBone_016', 'L_Foot'],
            ['MhBone_017', 'L_Toe'],

            ['MhBone_018', 'R_Thigh'],
            ['MhBone_019', 'R_Shin'],
            ['MhBone_020', 'R_Foot'],
            ['MhBone_021', 'R_Toe'],

            ['MhBone_071', 'L_Elbow_HJ_00'],
            ['MhBone_080', 'L_Deltoid_HJ_00'],
            ['MhBone_081', 'L_ForearmTwist_HJ_02'],

            ['MhBone_073', 'R_Elbow_HJ_00'],
            ['MhBone_082', 'R_Deltoid_HJ_00'],
            ['MhBone_083', 'R_ForearmTwist_HJ_02'],

            ['MhBone_074', 'L_Hip_HJ_01'],
            ['MhBone_075', 'L_Knee_HJ_00'],

            ['MhBone_076', 'R_Hip_HJ_01'],
            ['MhBone_077', 'R_Knee_HJ_00'],

            ['MhBone_070', 'L_Traps_HJ_01'],
            ['MhBone_072', 'R_Traps_HJ_01'],
        ]