# 编写字典时最好按照骨骼层级的顺序来编写，简单来说就是胯到胸到头，左臂到左手，右臂到右手，左腿到左脚，右腿到右脚。
# 注意，请确保rename_vg_fixed_name_list字典中的前5个骨骼名，普遍都存在于该字典对应的一类外部骨架中，插件会用于判定选择的字典是否匹配当前选中的外部骨架。

snap_bone_fixed_name_list = [
            ['MHBone_013', 'Hip'],
            ['MHBone_001', 'Spine_0'],
            ['MHBone_002', 'Spine_1'],
            ['MHBone_002', 'Spine_2'],
            ['MHBone_003', 'Neck_0'],
            ['MHBone_003', 'Neck_0_HJ_00'],

            ['MHBone_004', 'Head'],

            ['MHBone_005', 'L_Shoulder'],
            ['MHBone_080', 'L_UpperArm'],
            ['MHBone_007', 'L_Forearm'],
            ['MHBone_008', 'L_Hand'],
            ['MHBone_008', 'L_Wep'],

            ['MHBone_031', 'L_Thumb1'],
            ['MHBone_032', 'L_Thumb2'],
            ['MHBone_033', 'L_Thumb3'],

            ['MHBone_031', 'L_Thumb_HJ_00'],
            ['MHBone_032', 'L_Thumb_HJ_01'],
            ['MHBone_033', 'L_Thumb_HJ_02'],
            ['MHBone_031', 'L_Thumb_HJ_03'],

            ['MHBone_034', 'L_IndexF1'],
            ['MHBone_035', 'L_IndexF2'],
            ['MHBone_036', 'L_IndexF3'],

            ['MHBone_034', 'L_IndexF_HJ_01'],
            ['MHBone_035', 'L_IndexF_HJ_02'],
            ['MHBone_036', 'L_IndexF_HJ_03'],
            ['MHBone_034', 'L_IndexF_HJ_00'],
            ['MHBone_034', 'L_IndexF_HJ_04'],

            ['MHBone_037', 'L_MiddleF1'],
            ['MHBone_038', 'L_MiddleF2'],
            ['MHBone_039', 'L_MiddleF3'],

            ['MHBone_037', 'L_MiddleF_HJ_01'],
            ['MHBone_038', 'L_MiddleF_HJ_02'],
            ['MHBone_039', 'L_MiddleF_HJ_03'],
            ['MHBone_037', 'L_MiddleF_HJ_00'],
            ['MHBone_037', 'L_MiddleF_HJ_04'],

            ['MHBone_040', 'L_Palm'],

            ['MHBone_041', 'L_RingF1'],
            ['MHBone_042', 'L_RingF2'],
            ['MHBone_043', 'L_RingF3'],

            ['MHBone_041', 'L_RingF_HJ_01'],
            ['MHBone_042', 'L_RingF_HJ_02'],
            ['MHBone_043', 'L_RingF_HJ_03'],
            ['MHBone_041', 'L_RingF_HJ_00'],
            ['MHBone_041', 'L_RingF_HJ_04'],

            ['MHBone_044', 'L_PinkyF1'],
            ['MHBone_045', 'L_PinkyF2'],
            ['MHBone_046', 'L_PinkyF3'],

            ['MHBone_044', 'L_PinkyF_HJ_01'],
            ['MHBone_045', 'L_PinkyF_HJ_02'],
            ['MHBone_046', 'L_PinkyF_HJ_03'],
            ['MHBone_044', 'L_PinkyF_HJ_00'],
            ['MHBone_044', 'L_PinkyF_HJ_04'],

            ['MHBone_008', 'L_HandRZ_HJ_00'],
            ['MHBone_008', 'L_Hand_HJ_01'],
            ['MHBone_008', 'L_Wep_Sub'],
            ['MHBone_008', 'L_Hand_HJ_00'],

            ['MHBone_081', 'L_ForearmTwist_HJ_02'],
            ['MHBone_007', 'L_ForearmRY_HJ_00'],
            ['MHBone_007', 'L_ForearmRY_HJ_01'],
            ['MHBone_081', 'L_ForearmTwist_HJ_01'],
            ['MHBone_007', 'L_ForearmTwist_HJ_00'],
            ['MHBone_007', 'L_Forearm_HJ_00'],
            ['MHBone_007', 'L_Elbow_HJ_00'],

            ['MHBone_080', 'L_UpperArmTwist_HJ_00'],

            ['MHBone_006', 'L_UpperArmTwist_HJ_01'],
            ['MHBone_006', 'L_Triceps_HJ_00'],
            ['MHBone_006', 'L_Biceps_HJ_00'],
            ['MHBone_006', 'L_Biceps_HJ_01'],
            ['MHBone_006', 'L_UpperArmTwist_HJ_02'],

            ['MHBone_007', 'L_ForearmDouble_HJ_00'],
            ['MHBone_080', 'L_UpperArm_HJ_00'],
            ['MHBone_080', 'L_Deltoid_HJ_00'],
            ['MHBone_080', 'L_Deltoid_HJ_01'],
            ['MHBone_080', 'L_Deltoid_HJ_02'],
            ['MHBone_080', 'L_UpperArmDouble_HJ_00'],

            ['MHBone_005', 'L_Shoulder_HJ_00'],

            ['MHBone_009', 'R_Shoulder'],
            ['MHBone_082', 'R_UpperArm'],
            ['MHBone_011', 'R_Forearm'],
            ['MHBone_012', 'R_Hand'],
            ['MHBone_012', 'R_Wep'],

            ['MHBone_048', 'R_Thumb1'],
            ['MHBone_049', 'R_Thumb2'],
            ['MHBone_050', 'R_Thumb3'],

            ['MHBone_048', 'R_Thumb_HJ_00'],
            ['MHBone_049', 'R_Thumb_HJ_01'],
            ['MHBone_050', 'R_Thumb_HJ_02'],
            ['MHBone_048', 'R_Thumb_HJ_03'],

            ['MHBone_051', 'R_IndexF1'],
            ['MHBone_052', 'R_IndexF2'],
            ['MHBone_053', 'R_IndexF3'],

            ['MHBone_051', 'R_IndexF_HJ_01'],
            ['MHBone_052', 'R_IndexF_HJ_02'],
            ['MHBone_053', 'R_IndexF_HJ_03'],
            ['MHBone_051', 'R_IndexF_HJ_00'],
            ['MHBone_051', 'R_IndexF_HJ_04'],

            ['MHBone_054', 'R_MiddleF1'],
            ['MHBone_055', 'R_MiddleF2'],
            ['MHBone_056', 'R_MiddleF3'],

            ['MHBone_054', 'R_MiddleF_HJ_01'],
            ['MHBone_055', 'R_MiddleF_HJ_02'],
            ['MHBone_056', 'R_MiddleF_HJ_03'],
            ['MHBone_054', 'R_MiddleF_HJ_00'],
            ['MHBone_054', 'R_MiddleF_HJ_04'],

            ['MHBone_057', 'R_Palm'],

            ['MHBone_058', 'R_RingF1'],
            ['MHBone_059', 'R_RingF2'],
            ['MHBone_060', 'R_RingF3'],

            ['MHBone_058', 'R_RingF_HJ_01'],
            ['MHBone_059', 'R_RingF_HJ_02'],
            ['MHBone_060', 'R_RingF_HJ_03'],
            ['MHBone_058', 'R_RingF_HJ_00'],
            ['MHBone_058', 'R_RingF_HJ_04'],

            ['MHBone_061', 'R_PinkyF1'],
            ['MHBone_062', 'R_PinkyF2'],
            ['MHBone_063', 'R_PinkyF3'],

            ['MHBone_061', 'R_PinkyF_HJ_01'],
            ['MHBone_062', 'R_PinkyF_HJ_02'],
            ['MHBone_063', 'R_PinkyF_HJ_03'],
            ['MHBone_061', 'R_PinkyF_HJ_00'],
            ['MHBone_061', 'R_PinkyF_HJ_04'],

            ['MHBone_012', 'R_HandRZ_HJ_00'],
            ['MHBone_012', 'R_Hand_HJ_01'],
            ['MHBone_012', 'R_Wep_Sub'],
            ['MHBone_012', 'R_Hand_HJ_00'],

            ['MHBone_083', 'R_ForearmTwist_HJ_02'],
            ['MHBone_011', 'R_ForearmRY_HJ_00'],
            ['MHBone_011', 'R_ForearmRY_HJ_01'],
            ['MHBone_083', 'R_ForearmTwist_HJ_01'],
            ['MHBone_011', 'R_ForearmTwist_HJ_00'],
            ['MHBone_011', 'R_Shield'],
            ['MHBone_011', 'R_Forearm_HJ_00'],
            ['MHBone_011', 'R_Elbow_HJ_00'],

            ['MHBone_082', 'R_UpperArmTwist_HJ_00'],

            ['MHBone_010', 'R_UpperArmTwist_HJ_01'],
            ['MHBone_010', 'R_Triceps_HJ_00'],
            ['MHBone_010', 'R_Biceps_HJ_00'],
            ['MHBone_010', 'R_Biceps_HJ_01'],
            ['MHBone_010', 'R_UpperArmTwist_HJ_02'],

            ['MHBone_011', 'R_ForearmDouble_HJ_00'],
            ['MHBone_082', 'R_UpperArm_HJ_00'],
            ['MHBone_082', 'R_Deltoid_HJ_00'],
            ['MHBone_082', 'R_Deltoid_HJ_01'],
            ['MHBone_082', 'R_Deltoid_HJ_02'],
            ['MHBone_082', 'R_UpperArmDouble_HJ_00'],

            ['MHBone_009', 'R_Shoulder_HJ_00'],

            ['MHBone_005', 'L_Traps_HJ_00'],
            ['MHBone_005', 'L_Traps_HJ_01'],
            ['MHBone_005', 'L_Pec_HJ_00'],
            ['MHBone_005', 'L_Pec_HJ_01'],
            ['MHBone_005', 'L_Lats_HJ_00'],
            ['MHBone_005', 'L_Lats_HJ_01'],

            ['MHBone_009', 'R_Traps_HJ_00'],
            ['MHBone_009', 'R_Traps_HJ_01'],
            ['MHBone_009', 'R_Pec_HJ_00'],
            ['MHBone_009', 'R_Pec_HJ_01'],
            ['MHBone_009', 'R_Lats_HJ_00'],
            ['MHBone_009', 'R_Lats_HJ_01'],

            ['MHBone_002', 'Spine_2_HJ_00'],

            #    ['','R_Bust_HJ_00'],
            #    ['','R_Bust_HJ_01'],
            #    ['','L_Bust_HJ_00'],
            #    ['','L_Bust_HJ_01'],

            ['MHBone_002', 'Spine_1_HJ_00'],
            ['MHBone_001', 'Spine_0_HJ_00'],

            ['MHBone_014', 'L_Thigh'],
            ['MHBone_015', 'L_Knee'],
            ['MHBone_015', 'L_Shin'],
            ['MHBone_016', 'L_Foot'],

            ['MHBone_017', 'L_Toe'],
            ['MHBone_016', 'L_Foot_HJ_00'],
            ['MHBone_015', 'L_Calf_HJ_00'],
            ['MHBone_015', 'L_Shin_HJ_00'],
            ['MHBone_015', 'L_Shin_HJ_01'],
            ['MHBone_015', 'L_Knee_HJ_00'],
            ['MHBone_015', 'L_KneeDouble_HJ_00'],
            ['MHBone_015', 'L_KneeRX_HJ_00'],
            ['MHBone_014', 'L_ThighTwist_HJ_00'],
            ['MHBone_014', 'L_ThighTwist_HJ_01'],
            ['MHBone_015', 'L_ThighTwist_HJ_02'],

            ['MHBone_018', 'R_Thigh'],
            ['MHBone_019', 'R_Knee'],
            ['MHBone_019', 'R_Shin'],
            ['MHBone_020', 'R_Foot'],

            ['MHBone_021', 'R_Toe'],
            ['MHBone_020', 'R_Foot_HJ_00'],
            ['MHBone_019', 'R_Calf_HJ_00'],
            ['MHBone_019', 'R_Shin_HJ_00'],
            ['MHBone_019', 'R_Shin_HJ_01'],
            ['MHBone_019', 'R_Knee_HJ_00'],
            ['MHBone_019', 'R_KneeDouble_HJ_00'],
            ['MHBone_019', 'R_KneeRX_HJ_00'],
            ['MHBone_018', 'R_ThighTwist_HJ_00'],
            ['MHBone_018', 'R_ThighTwist_HJ_01'],
            ['MHBone_019', 'R_ThighTwist_HJ_02'],

            ['MHBone_014', 'L_ThighRZ_HJ_00'],
            ['MHBone_014', 'L_ThighRZ_HJ_01'],
            ['MHBone_018', 'R_ThighRZ_HJ_00'],
            ['MHBone_018', 'R_ThighRZ_HJ_01'],
            ['MHBone_014', 'L_Hip_HJ_00'],
            ['MHBone_014', 'L_Hip_HJ_01'],
            ['MHBone_018', 'R_Hip_HJ_00'],
            ['MHBone_018', 'R_Hip_HJ_01'],
            ['MHBone_014', 'L_ThighRX_HJ_00'],
            ['MHBone_014', 'L_ThighRX_HJ_01'],
            ['MHBone_018', 'R_ThighRX_HJ_00'],
            ['MHBone_018', 'R_ThighRX_HJ_01'],

            ['MHBone_013', 'Hip_HJ_00'],
        ]
        
rename_vg_fixed_name_list = [
            ['MHBone_000', 'COG'],
            ['MHBone_013', 'Hip_HJ_00'],
            ['MHBone_001', 'Spine_0_HJ_00'],
            ['MHBone_002', 'Spine_1_HJ_00'],
            ['MHBone_003', 'Neck_0_HJ_00'],
            ['MHBone_004', 'Head'],

            ['MHBone_005', 'L_Shoulder_HJ_00'],
            ['MHBone_006', 'L_UpperArmTwist_HJ_01'],
            ['MHBone_007', 'L_ForearmTwist_HJ_00'],
            ['MHBone_008', 'L_Hand'],
            ['MHBone_031', 'L_Thumb1'],
            ['MHBone_032', 'L_Thumb2'],
            ['MHBone_033', 'L_Thumb3'],
            ['MHBone_034', 'L_IndexF1'],
            ['MHBone_035', 'L_IndexF2'],
            ['MHBone_036', 'L_IndexF3'],
            ['MHBone_037', 'L_MiddleF1'],
            ['MHBone_038', 'L_MiddleF2'],
            ['MHBone_039', 'L_MiddleF3'],
            ['MHBone_040', 'L_Palm'],
            ['MHBone_041', 'L_RingF1'],
            ['MHBone_042', 'L_RingF2'],
            ['MHBone_043', 'L_RingF3'],
            ['MHBone_044', 'L_PinkyF1'],
            ['MHBone_045', 'L_PinkyF2'],
            ['MHBone_046', 'L_PinkyF3'],

            ['MHBone_009', 'R_Shoulder_HJ_00'],
            ['MHBone_010', 'R_UpperArmTwist_HJ_01'],
            ['MHBone_011', 'R_ForearmTwist_HJ_00'],
            ['MHBone_012', 'R_Hand'],
            ['MHBone_048', 'R_Thumb1'],
            ['MHBone_049', 'R_Thumb2'],
            ['MHBone_050', 'R_Thumb3'],
            ['MHBone_051', 'R_IndexF1'],
            ['MHBone_052', 'R_IndexF2'],
            ['MHBone_053', 'R_IndexF3'],
            ['MHBone_054', 'R_MiddleF1'],
            ['MHBone_055', 'R_MiddleF2'],
            ['MHBone_056', 'R_MiddleF3'],
            ['MHBone_057', 'R_Palm'],
            ['MHBone_058', 'R_RingF1'],
            ['MHBone_059', 'R_RingF2'],
            ['MHBone_060', 'R_RingF3'],
            ['MHBone_061', 'R_PinkyF1'],
            ['MHBone_062', 'R_PinkyF2'],
            ['MHBone_063', 'R_PinkyF3'],

            ['MHBone_014', 'L_Thigh'],
            ['MHBone_015', 'L_Shin'],
            ['MHBone_016', 'L_Foot'],
            ['MHBone_017', 'L_Toe'],

            ['MHBone_018', 'R_Thigh'],
            ['MHBone_019', 'R_Shin'],
            ['MHBone_020', 'R_Foot'],
            ['MHBone_021', 'R_Toe'],

            ['MHBone_071', 'L_Elbow_HJ_00'],
            ['MHBone_080', 'L_Deltoid_HJ_00'],
            ['MHBone_081', 'L_ForearmTwist_HJ_02'],

            ['MHBone_073', 'R_Elbow_HJ_00'],
            ['MHBone_082', 'R_Deltoid_HJ_00'],
            ['MHBone_083', 'R_ForearmTwist_HJ_02'],

            ['MHBone_074', 'L_Hip_HJ_01'],
            ['MHBone_075', 'L_Knee_HJ_00'],

            ['MHBone_076', 'R_Hip_HJ_01'],
            ['MHBone_077', 'R_Knee_HJ_00'],

            ['MHBone_070', 'L_Traps_HJ_01'],
            ['MHBone_072', 'R_Traps_HJ_01'],
        ]